### ISSUE TITLE
can't find the pretrained model?

### ISSUE THREAD

**Issue by GuideWsp** [huawei-noah/vega#1]

**Comment by zhangjiajin** [comment]
@GuideWsp We are uploading models to the server. These models can be downloaded in two days. Not all algorithms require pre-trained models. You can try algorithms that do not require pre-trained models.

**Comment by GuideWsp** [comment]
Thanks for you reply.

**Comment by zhangjiajin** [comment]
All models are available for download, please try it. @GuideWsp
