### ISSUE TITLE
The selection steps of CARS_NSGA (pNSGA-III).

### ISSUE THREAD

**Issue by 1ziyanW1** [huawei-noah/vega#105]
Hello! I have a question about pNSGA-III in CARS. The selection step after non dominated sorting of CARS_ NSGA is just to merge the two Pareto fronts. Rather than use the traditional NSGA-III reference point based selection ?

**Comment by zhaohui-yang** [comment]
Dear 1ziyanW1, thanks for your attention. You are right. We merged two Pareto fronts and did not use the reference point based selection because we thought it was not that critical. In the released code, the standard NSGA-III is implemented, and you could try if you want.

**Comment by 1ziyanW1** [comment]
Thank you very much for your reply! I have encountered a new problem. I am not clear about the steps of applying the architectures obtained in CARS to other datasets. I have two understandings. One is to run nas steps on CIFAR10 to get the architectures, and then run fullytrain steps on other datasets. Second, run nas and fullytrain steps on CIFAR10 to get the architectures, and then run fullytrain steps on other datasets again. Or the two understandings are wrong, can you tell me the correct order? Looking forward to your reply!

**Comment by 1ziyanW1** [comment]
> Dear 1ziyanW1, thanks for your attention. You are right. We merged two Pareto fronts and did not use the reference point based selection because we thought it was not that critical. In the released code, the standard NSGA-III is implemented, and you could try if you want.

Thank you very much for your reply! I have encountered a new problem. I am not clear about the steps of applying the architectures obtained in CARS to other datasets. I have two understandings. One is to run nas steps on CIFAR10 to get the architectures, and then run fullytrain steps on other datasets. Second, run nas and fullytrain steps on CIFAR10 to get the architectures, and then run fullytrain steps on other datasets again. Or the two understandings are wrong, can you tell me the correct order? Looking forward to your reply!

**Comment by zhaohui-yang** [comment]
@1ziyanW1 Step1: run nas steps on CIFAR10 and get the architectures. Step2: Retrain the architectures on CIFAR10 and other datasets.
