### ISSUE TITLE
AvazuDataset  for AutoFIS

### ISSUE THREAD

**Issue by TiaoziLiao** [huawei-noah/vega#106]
How do you process the data set?
I run the examples/nas/fis/autogate_grda.yml, but it got wrong.
![image](https://user-images.githubusercontent.com/58799823/113814325-0ccb1a80-97a4-11eb-8546-e647db616e23.png)

I downloaded the data set on Kaggle and unzipped it, however the train and test dataset are .csv file. It wasn't an .npy file.
![image](https://user-images.githubusercontent.com/58799823/113814962-08ebc800-97a5-11eb-8646-6b4afc1e6f5b.png)

So, is there any shell to preprocesses the dataset Avazu？

**Comment by TiaoziLiao** [comment]
![image](https://user-images.githubusercontent.com/58799823/113810842-ac38df00-979d-11eb-80d9-2ce292e0c402.png)

**Comment by kinglai** [comment]
We follow the data preprocess progress in [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) , and then transform data from hdf5 format into numpy format. thx.

**Comment by TiaoziLiao** [comment]
I got the .h5 file of Avazu from [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) can you provide a script to convert it to .npy file?

**Comment by TiaoziLiao** [comment]
> We follow the data preprocess progress in [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) , and then transform data from hdf5 format into numpy format. thx.

I got the .h5 file of Avazu from Ads-RecSys-Datasets can you provide a script to convert it to .npy file?

**Comment by TiaoziLiao** [comment]
> We follow the data preprocess progress in [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) , and then transform data from hdf5 format into numpy format. thx.

My file structure is as follows
-- Avazu
    |-- hdf
    |   |-- test_input_part_0.h5
    |   |-- test_input_part_1.h5
    |   |-- test_input_part_2.h5
    |   |-- test_input_part_3.h5
    |   |-- test_input_part_4.h5
    |   |-- test_output_part_0.h5
    |   |-- test_output_part_1.h5
    |   |-- test_output_part_2.h5
    |   |-- test_output_part_3.h5
    |   |-- test_output_part_4.h5
    |   |-- train_input_part_0.h5
    |   |-- train_input_part_1.h5
    |   |-- train_input_part_10.h5
    |   |-- train_input_part_11.h5
    |   |-- train_input_part_12.h5
    |   |-- train_input_part_13.h5
    |   |-- train_input_part_14.h5
    |   |-- train_input_part_15.h5
    |   |-- train_input_part_16.h5
    |   |-- train_input_part_2.h5
    |   |-- train_input_part_3.h5
    |   |-- train_input_part_4.h5
    |   |-- train_input_part_5.h5
    |   |-- train_input_part_6.h5
    |   |-- train_input_part_7.h5
    |   |-- train_input_part_8.h5
    |   |-- train_input_part_9.h5
    |   |-- train_output_part_0.h5
    |   |-- train_output_part_1.h5
    |   |-- train_output_part_10.h5
    |   |-- train_output_part_11.h5
    |   |-- train_output_part_12.h5
    |   |-- train_output_part_13.h5
    |   |-- train_output_part_14.h5
    |   |-- train_output_part_15.h5
    |   |-- train_output_part_16.h5
    |   |-- train_output_part_2.h5
    |   |-- train_output_part_3.h5
    |   |-- train_output_part_4.h5
    |   |-- train_output_part_5.h5
    |   |-- train_output_part_6.h5
    |   |-- train_output_part_7.h5
    |   |-- train_output_part_8.h5
    |   `-- train_output_part_9.h5
    `-- npy

**Comment by kinglai** [comment]
```pytyhon
data = pd.read_hdf(f_in_name).as_matrix()
np.save(np_data_path, data)
```

Run it for all your h5 data files.

> > We follow the data preprocess progress in [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) , and then transform data from hdf5 format into numpy format. thx.
> 
> My file structure is as follows
> -- Avazu
> |-- hdf
> | |-- test_input_part_0.h5
> | |-- test_input_part_1.h5
> | |-- test_input_part_2.h5
> | |-- test_input_part_3.h5
> | |-- test_input_part_4.h5
> | |-- test_output_part_0.h5
> | |-- test_output_part_1.h5
> | |-- test_output_part_2.h5
> | |-- test_output_part_3.h5
> | |-- test_output_part_4.h5
> | |-- train_input_part_0.h5
> | |-- train_input_part_1.h5
> | |-- train_input_part_10.h5
> | |-- train_input_part_11.h5
> | |-- train_input_part_5.h5
> | |-- train_input_part_6.h5
> | |-- train_input_part_7.h5
> | |-- train_input_part_8.h5
> | |-- train_input_part_9.h5
> | |-- train_output_part_0.h5
> | |-- train_output_part_11.h5
> | |-- train_output_part_12.h5
> | |-- train_output_part_13.h5
> | |-- train_output_part_14.h5
> | |-- train_output_part_15.h5
> | |-- train_output_part_16.h5
> | |-- train_output_part_2.h5
> | |-- train_output_part_3.h5
> | |-- train_output_part_4.h5
> | |-- train_output_part_8.h5
> | `-- train_output_part_9.h5 `-- npy

**Comment by TiaoziLiao** [comment]
> ```
> data = pd.read_hdf(f_in_name).as_matrix()
> np.save(np_data_path, data)
> ```
> 
> Run it for all your h5 data files.
> 
> > > We follow the data preprocess progress in [Ads-RecSys-Datasets](https://github.com/Atomu2014/Ads-RecSys-Datasets) , and then transform data from hdf5 format into numpy format. thx.
> > 
> > 
> > My file structure is as follows
> > -- Avazu
> > |-- hdf
> > | |-- test_input_part_0.h5
> > | |-- test_input_part_1.h5
> > | |-- test_input_part_2.h5
> > | |-- test_input_part_3.h5
> > | |-- test_input_part_4.h5
> > | |-- test_output_part_0.h5
> > | |-- test_output_part_1.h5
> > | |-- test_output_part_2.h5
> > | |-- test_output_part_3.h5
> > | |-- test_output_part_4.h5
> > | |-- train_input_part_0.h5
> > | |-- train_input_part_1.h5
> > | |-- train_input_part_10.h5
> > | |-- train_input_part_11.h5
> > | |-- train_input_part_5.h5
> > | |-- train_input_part_6.h5
> > | |-- train_input_part_7.h5
> > | |-- train_input_part_8.h5
> > | |-- train_input_part_9.h5
> > | |-- train_output_part_0.h5
> > | |-- train_output_part_11.h5
> > | |-- train_output_part_12.h5
> > | |-- train_output_part_13.h5
> > | |-- train_output_part_14.h5
> > | |-- train_output_part_15.h5
> > | |-- train_output_part_16.h5
> > | |-- train_output_part_2.h5
> > | |-- train_output_part_3.h5
> > | |-- train_output_part_4.h5
> > | |-- train_output_part_8.h5
> > | `-- train_output_part_9.h5 `-- npy

thank for your replay, i will try in this way
