### ISSUE TITLE
issue with fully_train step in the provided modnas DARTS example

### ISSUE THREAD

**Issue by aswanthkrishna** [huawei-noah/vega#112]
I am trying to run the examples provided for modnas darts algorithm. The search stage of the algorithm works perfectly fine the best architecture is getting exported to "{local_worker_path}/exp/default/outputs/arch_search_best.yaml"  but errors are popping up in fully train step
From the provided documentation i am supposed to pass obtained arch_desc file to train Pipestep in the following way

`search_space:
  type: SearchSpace
  modules: [custom]
  custom:
    type: ModNasArchSpace
    model:
      ...
    construct:
      ... # search space constructor
    desc_construct:
      arch_desc:
        type: # arch. desc. constructor
`

however passing the path as argument to "arch_desc" is not solving the problem. Can someone tell me how to properly add arch_desc in the config file. also Thank you for this great library :)

**Comment by hujx0** [comment]
The document description is not particularly accurate. The path should be passed as a as argument to “fully_train.model.model_desc_file”.
![image](https://user-images.githubusercontent.com/84825820/119597917-8da5aa80-be14-11eb-8fd5-d96f16022966.png)

**Comment by hujx0** [comment]
@

> I am trying to run the examples provided for modnas darts algorithm. The search stage of the algorithm works perfectly fine the best architecture is getting exported to "{local_worker_path}/exp/default/outputs/arch_search_best.yaml" but errors are popping up in fully train step
> From the provided documentation i am supposed to pass obtained arch_desc file to train Pipestep in the following way
> 
> `search_space: type: SearchSpace modules: [custom] custom: type: ModNasArchSpace model: ... construct: ... # search space constructor desc_construct: arch_desc: type: # arch. desc. constructor `
> 
> however passing the path as argument to "arch_desc" is not solving the problem. Can someone tell me how to properly add arch_desc in the config file. also Thank you for this great library :)

The document description is not particularly accurate. The path should be passed as a as argument to      “fully_train.model.model_desc_file”. 
![image](https://user-images.githubusercontent.com/84825820/119598512-ac587100-be15-11eb-977e-97357e5fe3ca.png)

**Comment by aswanthkrishna** [comment]
this did not solve the problem. However I can run the fully_train step separately by loading the searched model from arch_desc by adding this in the config file.
```       model_desc:
            modules: [custom]
            custom:
                type: ModNasArchSpace
                fully_train: True
                model:
                    type: CIFAR_MobileNetV2_GPU
                    args:
                        n_classes: 10
                desc_construct:
                    torch:
                        type: MobileNetV2ArchDescConstructor
                        args:
                            arch_desc: "/home/ubuntu/vega_new/tasks/0519.174421.182/workers/nas/0/exp/default/output/arch_search_best.yaml"
                    ```

**Comment by CreeperLin** [comment]
> this did not solve the problem. However I can run the fully_train step separately by loading the searched model from arch_desc by adding this in the config file.
> 
> ```
>             modules: [custom]
>             custom:
>                 type: ModNasArchSpace
>                 fully_train: True
>                 model:
>                     type: CIFAR_MobileNetV2_GPU
>                     args:
>                         n_classes: 10
>                 desc_construct:
>                     torch:
>                         type: MobileNetV2ArchDescConstructor
>                         args:
>                             arch_desc: "/home/ubuntu/vega_new/tasks/0519.174421.182/workers/nas/0/exp/default/output/arch_search_best.yaml"
>                     ```
> ```

As for the YAML configuration, the intended place to specify the arch_desc when running fully_train step is "model.model_desc.custom.arch_desc":

```yaml
modules: [custom]
    custom:
        type: ModNasArchSpace
        fully_train: True
        model:
            type: CIFAR_MobileNetV2_GPU
            args:
                n_classes: 10
        desc_construct:
            torch:
                type: MobileNetV2ArchDescConstructor
        arch_desc: ### path to arch_desc yaml file, or arch_desc object itself
```

I will note this in the documentations, thank you! @aswanthkrishna

**Comment by aswanthkrishna** [comment]
thanks a lot. the issue is solved. Can you provide me an example config file on creating DARTSsearch space within modnas?
