### ISSUE TITLE
vega: command not found

### ISSUE THREAD

**Issue by vanessasidrim** [huawei-noah/vega#114]
I performed the installation following the instructions in the install.md file, but when I try to run the vega command, I get "vega: command not found"

**Comment by zhangjiajin** [comment]
@vanessasidrim

**Comment by vanessasidrim** [comment]
The vega command worked, however, when trying to run SPNAS on several gpus using the vega.pipeline command, a No module named error is returned

**Comment by zhangjiajin** [comment]
@vanessasidrim 

Please provide more detailed information, such as logs.

**Comment by vanessasidrim** [comment]
I try execute `CUDA_VISIBLE_DEVICES=3,4,5 vega.pipeline ./nas/sp_nas/spnas.yml` and get as return bash: vega.pipeline: command not found

**Comment by zhangjiajin** [comment]
@vanessasidrim 

```bash
CUDA_VISIBLE_DEVICES=3,4,5 vega ./nas/sp_nas/spnas.yml
```

**Comment by vanessasidrim** [comment]
I tried this but the following error is returned to me:

Notes: 
-  msgpack: Variation is ok, as long as everything is above 0.6
-  python: Variation is sometimes ok, sometimes not. It depends on your workloads
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\xd7\x01\x00\x00\x00\x00\x00\x00\x8c\x1evega.core.scheduler.worker_env\x94\x8c\tWorkerEnv\x94\x93\x94)\x81\x94}\x94(\x8c\x11workers_each_node\x94K\x01\x8c\x0cdevice_quota\x94K\x03\x8c\x10master_host_name\x94N\x8c\nmaster_pid\x94M\x13<\x8c\x0bdevice_list\x94]\x94\x8c\r_backend_type\x94\x8c\x07PYTORCH\x94\x8c\x0fdevice_category\x94\x8c\x03GPU\x94\x8c\ttemp_path\x94\x8c)/vega/examples/tasks/0528.093414.763/temp\x94\x8c\x14__worker_null_file__\x94\x8c4/vega/examples/tasks/0528.093414.763/temp/.vega_null\x94\x8c\x18__worker_device_folder__\x94\x8c6/vega/examples/tasks/0528.093414.763/temp/.vega_device\x94\x8c\r_cuda_devices\x94]\x94(\x8c\x013\x94\x8c\x014\x94\x8c\x015\x94e\x8c\x14_ori_rank_table_file\x94Nub.'
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 67, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'vega'
distributed.utils - ERROR - No module named 'vega'

**Comment by vanessasidrim** [comment]
I tried this but the following error is returned to me:

Notes:
- msgpack: Variation is ok, as long as everything is above 0.6
- python: Variation is sometimes ok, sometimes not. It depends on your workloads
  warnings.warn (version_module.VersionMismatchWarning (msg [0] ["warning"]))
distributed.protocol.pickle - INFO - Failed to deserialize b '\ x80 \ x04 \ x95 \ xd7 \ x01 \ x00 \ x00 \ x00 \ x00 \ x00 \ x00 \ x8c \ x1evega.core.scheduler.worker_env \ x94 \ x8c \ tWorkerEnv \ x94 \ x93 \ x94) \ x81 \ x94} \ x94 (\ x8c \ x11workers_each_node \ x94K \ x01 \ x8c \ x0cdevice_quota \ x94K \ x03 \ x8c \ x10master_host_name \ x94N \ x8c \ nmaster_pid \ x94 \ xmaster \ x0bdevice_list \ x94] \ x94 \ x8c \ r_backend_type \ x94 \ x8c \ x07PYTORCH \ x94 \ x8c \ x0fdevice_category \ x94 \ x8c \ x03GPU \ x94 \ x8c \ ttemp_path \ x94/ x8c/7/8/8/9/8/9/9/9/9/8x8x8/9x8x8/8/8/8/8/8/8/8/8/8/8/8/8x8/8/8/8/8/8x8/8/8/8x8/8/8x8x8/ both temp \ x94 \ x8c \ x14__worker_null_file __ \ x94 \ x8c4 / vega / examples / tasks / 0528.093414.763 / temp / .vega_null \ x94 \ x8c \ x18__worker_device_folder __ \ x94 \ x8c6 / vega / examples / tasks / 0528.0934. vega_device \ x94 \ x8c \ r_cuda_devices \ x94] \ x94 (\ x8c \ x013 \ x94 \ x8c \ x014 \ x94 \ x8c \ x015 \ x94e \ x8c \ x14_ori_rank_table_file \ x94Nub. '
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 67, in loads
    return pickle.loads (x)
ModuleNotFoundError: No module named 'vega'
distributed.utils - ERROR - No module named 'vega'

**Comment by zhangjiajin** [comment]
@vanessasidrim 

It is possible that the Vega was not installed properly.

Run the following commands to install and pay attention to the information displayed during the installation:

```bash
pip3 install --user -U noah-vega
```

**Comment by vanessasidrim** [comment]
The problem had occurred when installing the dark, I need to install the library in the environment
