### ISSUE TITLE
Runtime error in CARS example

### ISSUE THREAD

**Issue by aswanthkrishna** [huawei-noah/vega#115]
I am trying to run the example provided on CARS algorithm. The search phase is running fine, getting the following runtime error in the fully train phase.

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 144, 8, 8]], which is output 0 of AddBackward0, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)`

How can I solve this?

**Comment by zhangjiajin** [comment]
@aswanthkrishna 

Please attach complete logs and the software version (pip3 list > all_pkgs.txt) of the environment to analyze the cause of the problem.

**Comment by aswanthkrishna** [comment]
it is solved. thank you!
