### ISSUE TITLE
questionsw about the ESRN

### ISSUE THREAD

**Issue by yyknight** [huawei-noah/vega#129]
Thanks for your impressive work. I noticed the provided ESRN model in model_zoo is not the same to the result in your AAAI paper. Could you kindly release the model and searched arch that is reported in your paper (ESRN and ESRN-V)?

**Comment by sven9972** [comment]
The CARS has the same situation, it is a bit confusing.

**Comment by zhangjiajin** [comment]
@yyknight 

Vega's ModelZoo provides models based on algorithms implemented by Vega.
Do these models meet your needs?

**Comment by yyknight** [comment]
> @yyknight
> 
> Vega's ModelZoo provides models based on algorithms implemented by Vega.
> Do these models meet your needs?

Thanks for your reply! I have checked the models provided in https://github.com/huawei-noah/vega/blob/master/docs/model_zoo.md
However, these provided model are not the same to the one recorded in your paper. Therefore, are these models provided in your paper available?

**Comment by yyknight** [comment]
> @yyknight
> 
> Vega's ModelZoo provides models based on algorithms implemented by Vega.
> Do these models meet your needs?

Thanks for your reply! I have checked the models provided in https://github.com/huawei-noah/vega/blob/master/docs/model_zoo.md
However, these provided model are not the same to the one recorded in your paper. Therefore, are these models provided in your paper available?

**Comment by zhangjiajin** [comment]
The original model in the paper is replaced by Vega's model.
We will not release the original model in the paper.

**Comment by yyknight** [comment]
Ok, I got it. Thanks for your reply
