### ISSUE TITLE
When will the SM-NAS be released

### ISSUE THREAD

**Issue by qgh1223** [huawei-noah/vega#131]
When will the SM-NAS be released?
I found some codes related to SMNAS. How to use it?
Whether you have released all the source code?

**Comment by zhangjiajin** [comment]
@qgh1223 

Which codes are related to the SM-NAS algorithm?
We are still benchmarking the SM-NAS algorithm and have no plans to release it in the near future.
The Backbone NAS algorithm comes from SM-NAS. 
This algorithm provides NAS for ResNet.
