### ISSUE TITLE
SP-NAS with custom dataset

### ISSUE THREAD

**Issue by vanessasidrim** [huawei-noah/vega#132]
Is it possible to run an SP-NAS with a custom object detection dataset (ie my own dataset)?

OBS: My current dataset follows the PascalVOC annotation and organization pattern.

**Comment by zhangjiajin** [comment]
@vanessasidrim 

Currently, the Pascal/VOC dataset can not be directly used.
You can use the Pascal/VOC format to COCO format tools to convert the dataset format.
