### ISSUE TITLE
vega训练过程中存在大量的锁文件任意用户可读

### ISSUE THREAD

**Issue by jiangzc86** [huawei-noah/vega#147]
![image](https://user-images.githubusercontent.com/7298945/135424565-7d147be8-5402-4e00-a29d-4aae917d7811.png)
![image](https://user-images.githubusercontent.com/7298945/135424576-a7c42d3a-1aa2-4407-80d2-c4e2c218cd2c.png)

**Comment by zhangjiajin** [comment]
vega产生的文件，应该和用户的umask配置相符合，不应该修改文件权限。
