### ISSUE TITLE
评估服务器，请求参数job_id未做校验可被设置成相对路径，可导致抛异常 最终进程复位

### ISSUE THREAD

**Issue by hdulinjian** [huawei-noah/vega#148]
![image](https://user-images.githubusercontent.com/35563851/135424774-a8c46263-ef37-44f1-9d89-7a075fa46d33.png)
![image](https://user-images.githubusercontent.com/35563851/135424793-2ae0eb05-aedc-4c4d-9f17-930ce7bb476b.png)
![image](https://user-images.githubusercontent.com/35563851/135424798-4f2f601b-0f43-4dca-8640-7fcf41d52b60.png)
![image](https://user-images.githubusercontent.com/35563851/135424812-6aa5188a-b39a-4b02-b9ce-dbc5ef42bf92.png)

**Comment by zhangjiajin** [comment]
```yaml
    def post(self):
        """Interface to response to the post request of the client."""
        try:
            self.parse_paras()
            self.upload_files()
            self.hardware_instance = ClassFactory.get_cls(self.hardware)(self.optional_params)
        except Exception:
            self.result["status"] = "Params error."
            self.result["error_message"] = traceback.format_exc()
            logging.error("[ERROR] Params error!")
            traceback.print_exc()
            return self.result
```
