### ISSUE TITLE
vega-evaluate-service 侧存在大量文件权限设置不当，请严格按照《Unix与Linux文件目录权限设计指导》和《 身份和访问管理安全设计规范》来实施,注意即便是开源组件也要符合要求

### ISSUE THREAD

**Issue by jiangzc86** [huawei-noah/vega#155]
![image](https://user-images.githubusercontent.com/7298945/135425438-7cdd79fc-74e5-4b11-b6bf-7933c6577a24.png)
<html>
<body>
<div class="quill-better-table-wrapper" style="overflow: auto;">

文件类型 | 设置值
-- | --
用户主目录 | 750（rwxr-x---）
程序文件(含脚本文件、库文件等) | 550（r-xr-x---）
程序文件目录 | 550（r-xr-x---）
配置文件 | 640（rw-r-----）
配置文件目录 | 750（rwxr-x---）
日志文件(记录完毕或者已经归档) | 440（r--r-----）
日志文件(正在记录) | 640（rw-r-----）
日志文件目录 | 750（rwxr-x---）
Debug文件 | 640（rw-r-----）
Debug文件目录 | 750（rwxr-x---）
临时文件目录 | 750（rwxr-x---）
维护升级文件目录 | 770（rwxrwx---）
业务数据文件 | 640（rw-r-----）
业务数据文件目录 | 750（rwxr-x---）
密钥、证书、密文文件目录 | 700（rwx—----）
密钥组件、私钥、证书、加密密文 | 600（rw-------）
加解密接口、加解密脚本 | 500（r-x------）

</div>
</body>
</html>

**Comment by zhangjiajin** [comment]
vega产生的文件，应该和用户的umask配置相符合，不应该修改文件权限。
