### ISSUE TITLE
vega评估服务器，请求参数repeat_times未做校验可导致抛异常 可导致进程复位

### ISSUE THREAD

**Issue by jiangzc86** [huawei-noah/vega#156]
![image](https://user-images.githubusercontent.com/7298945/135425606-3baf24b7-768e-4087-ae36-998376da5486.png)
![image](https://user-images.githubusercontent.com/7298945/135425618-0a0e9708-0081-4314-9f36-35fd3f2f87c9.png)
![image](https://user-images.githubusercontent.com/7298945/135425634-d2618ea5-8e16-4cd8-bb89-837d582d286f.png)
![image](https://user-images.githubusercontent.com/7298945/135425648-570dab94-a17b-4d95-a2b2-545a0d7df7c3.png)

**Comment by zhangjiajin** [comment]
```python
    def post(self):
        """Interface to response to the post request of the client."""
        try:
            self.parse_paras()
            self.upload_files()
            self.hardware_instance = ClassFactory.get_cls(self.hardware)(self.optional_params)
        except Exception:
            self.result["status"] = "Params error."
            self.result["error_message"] = traceback.format_exc()
            logging.error("[ERROR] Params error!")
            traceback.print_exc()
            return self.result
```
