### ISSUE TITLE
Is `regnition` a typo of reignite ?

### ISSUE THREAD

**Issue by sisrfeng** [huawei-noah/vega#171]
Is `regnition` a typo of reignite ?
`regnition: False            # Whether ImageNet has been performed. regnite#`
https://github.com/huawei-noah/vega/blob/master/docs/en/algorithms/sp_nas.md

**Comment by zhangjiajin** [comment]
@sisrfeng 

Sorry. This document is out of date.
W'll refresh it as soon as possible.
Thank you for pointing out this mistake, the parameter is not right.

**Comment by sisrfeng** [comment]
请问你们是优先更新中文文档吗？

**Comment by zhangjiajin** [comment]
中英文同时刷新。

**Comment by zhangjiajin** [comment]
预计今天完成，你可以先使用：
<https://github.com/huawei-noah/vega/blob/master/examples/nas/sp_nas/spnas.yml>

配置项参考，如下配置项可以配置在上面的yml文件中：
<https://github.com/huawei-noah/vega/blob/master/vega/algorithms/nas/sp_nas/conf.py>

**Comment by zhangjiajin** [comment]
@sisrfeng 

我们发现了一个和reignite相关的bug，大概在本周内可以解决，到时会刷新代码和文档。
请稍等。

**Comment by sisrfeng** [comment]
Is this file useless now?

examples/nas/sp_nas/spnas_md.yml

**Comment by zhangjiajin** [comment]
@sisrfeng 
2 different implements.
`spnas_md.yml` is a MindSpore version that provides better performance on Ascend 910.
`spnas.yml` is a Pytorch version and is better on GPUs.
