### ISSUE TITLE
This link is invalid now:   /examples/nas/sp_nas.yml

### ISSUE THREAD

**Issue by sisrfeng** [huawei-noah/vega#172]
https://github.com/huawei-noah/vega/blob/master/docs/en/algorithms/sp_nas.md
This link is invalid now: 
https://github.com/huawei-noah/vega/tree/master/examples/nas/sp_nas.yml

**Comment by zhangjiajin** [comment]
@sisrfeng 

The valid link:
<https://github.com/huawei-noah/vega/blob/master/examples/nas/sp_nas/spnas.yml>

We'll fix the error in sp_nas.md as soon as possible.
