### ISSUE TITLE
ERROR Failed to create instance:<class '* vega.networks.faster_rcnn.FasterRCNN'>

### ISSUE THREAD

**Issue by sisrfeng** [huawei-noah/vega#183]
Hi, I get the error:
` Failed to create instance:<class '* vega.networks.faster_rcnn.FasterRCNN'>`
I can not find the model `fasterrcnn_resnet50_fpn_coco-258fb6c6.pth` which is shown in yml file, I only download :
fasterrcnn_serialnet_backbone.pth
fasterrcnn_coco.pth

How to solve it ? 
Thx!

**Comment by zhangjiajin** [comment]
Here:

<https://github.com/huawei-noah/vega/blob/master/docs/cn/user/examples.md#21-%E8%BF%90%E8%A1%8Cpytorch%E7%A4%BA%E4%BE%8B>
<https://github.com/huawei-noah/vega/blob/master/docs/en/user/examples.md#21-run-pytorch-example>

**Comment by dawncc** [comment]
fasterrcnn_resnet50_fpn_coco-258fb6c6.pth is the weight file from torchvision: 
 https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
We have added a finetune pipestep in spnas.yml to convert torchvision weight file into spnas. kindly update the latest code.
