### ISSUE TITLE
Flops in model_zoo.md is not matched w/ model in model zoo

### ISSUE THREAD

**Issue by chanilP** [huawei-noah/vega#190]
Hi,

I export CULane-s to onnx and calculate FLOPs from the onnx file but my calculation result is not matched w/ FLOPs in model_zoo.md(66.5GFlops)

So, can you let me know how 66.5GFlops is calculated?

I used 288, 512 as input size (height, width).

Thanks

**Comment by Lzc06** [comment]
We will try to calculate FLOPs and reply you as soon as possible @chanilP
