### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'warmup'

### ISSUE THREAD

**Issue by Hukongtao** [huawei-noah/vega#192]
I am trying to run the quick_start example,  
https://github.com/huawei-noah/vega/blob/master/docs/cn/developer/quick_start.md,  
but I got the error

**Comment by Prokrus** [comment]
Hallo, I met the same error, how did you solve it? Thanks.

**Comment by Hukongtao** [comment]
> Hallo, I met the same error, how did you solve it? Thanks.

把yaml文件中有个warmup的参数注释了
