### ISSUE TITLE
Where to find download the vega-0.9.1-py3-none-any.whl ?

### ISSUE THREAD

**Issue by AyeshaNirma** [huawei-noah/vega#20]
Probably because of the fact I am new to vega but I cannot find this wheel `vega-0.9.1-py3-none-any.whl`. It says on the installation page  `download the vega-0.9.1-py3-none-any.whl file in the release directory `
Where is the release directory if someone can kindly point out.
I know we can built from the source but I would like to see.

**Comment by zhangjiajin** [comment]
@AyeshaNirma

**Comment by AyeshaNirma** [comment]
Yep found it thanks.
