### ISSUE TITLE
src_path' is not defined

### ISSUE THREAD

**Issue by vanessasidrim** [huawei-noah/vega#203]
When running SP-NAS I get the following error:
**ERROR:root:Failed to run worker, id: 19, message: name 'src_path' is not defined**

Where do I set the "src_path"?

**Comment by zhangjiajin** [comment]
@vanessasidrim 
Thank you for helping to find a bug.
Please update `vega/common/file_ops.py` and `vega/model_zoo/model_zoo.py`.

**Comment by vanessasidrim** [comment]
I performed a pull from master, the code was updated but the runtime error remains. 😢

**Comment by zhangjiajin** [comment]
@vanessasidrim 

Please uninstall noah-vega and reinstall it.

```shell
pip3 uninstall noah-vega
```

Then build vega.

```shell
cd vega
python3 ./setup.py bdist_wheel
```

Then reinstall vega.

```shell
cd dist
pip3 install ./noah_vega-1.8.0-py3-none-any.whl
```

Then run SP-NAS.

If runtime error remains, please provide logs.
