### ISSUE TITLE
 No module named 'vega.trainer'

### ISSUE THREAD

**Issue by litingsjj** [huawei-noah/vega#207]
I got this error, when use pip install  vega and pip install noah-vega.

**Comment by litingsjj** [comment]
另外使用pip安装之后，想修改源码比较烦，请问有开发者模式安装的教程吗？使用：python3 ./setup.py install，但是还是报同样的错误

**Comment by zhangjiajin** [comment]
@litingsjj 

下载源码，设置 `PYTHONPATH` 环境变量到源码目录，运行vega命令时就会加载源码目录的代码。

```shell
unzip master.zip
export PYTHONPATH=$(pwd)/master:$PYTHONPATH
vega ./master/examples/nas/cars/cars.yml
```

另外请提供更详细的错误日志信息。
