### ISSUE TITLE
请问Op_search能提供一些参考资料吗？

### ISSUE THREAD

**Issue by graceyangfan** [huawei-noah/vega#217]
这个和google的Automl Zero是类似的吗？都是通过类遗传算法的方式实现自动特征工程吗？

**Comment by zhangjiajin** [comment]
参考了AutoML-Zero关于搜索空间的构建思想，其他的和AutoML-Zero没有关系了。

op-search的目标和AutoML-Zero的目标不同。op-search是针对某个待优化的算子，搜索可以替代该算子的更优化的算子，优化目标主要是性能。
op-search使用了随机和简单的进化算法。

代码不多且独立，你可以看看代码。

**Comment by graceyangfan** [comment]
十分感谢
