### ISSUE TITLE
Can't find quantized weights 

### ISSUE THREAD

**Issue by L-ED** [huawei-noah/vega#224]
After finish of quant-ea algorithm i checked {vega_dir}/tasks/{experiment_number}/output/fully_train and nas directories. I loaded weights and assumed that they would be in 8 or 4 bit format, but weights was in float format. Is your search using fake-quantization?

**Comment by dawncc** [comment]
real quantization in pytorch is not supported, we define a fake-quantization operator in quant-ea algorithm for simulation.
