### ISSUE TITLE
vega目前是只支持单机版本的AutoML么

### ISSUE THREAD

**Issue by eedalong** [huawei-noah/vega#234]
我看distribute_worker似乎并没有具体实现

**Comment by zhangjiajin** [comment]
Vega 在搜索阶段，支持多个模型同时搜索。比如有三台主机，每台主机有8张V100卡，那么一次可以从搜索空间中搜索24个模型分布对应到每个独立的卡上训练评估。目前不支持模型同时搜索的算法有CARS、DARTS、ModularNAS，除此之外都支持同时搜索。

Vega 在完整训练阶段，支持 数据并行加速训练。

**Comment by XGBoost** [comment]
请问如何设置并行搜索呢？@zhangjiajin
