### ISSUE TITLE
[Bug] Fix the bug in  Sp-NAS test.py

### ISSUE THREAD

**Issue by hasanirtiza** [huawei-noah/vega#24]
Similar to the bug reported in #19 #23. The following line in test.py is also redundant and it causes the code to crash in second stage of training.

https://github.com/huawei-noah/vega/blob/fc8f30c9390dac12068714a2982f4366c0d27361/vega/algorithms/nas/sp_nas/tools/test.py#L193

**Comment by zhangjiajin** [comment]
Yes, line 193 in test.py is redundant. This bug was fixed, please try again.

**Comment by hasanirtiza** [comment]
Works, thanks.
