### ISSUE TITLE
Is there no code about guilded mutation in esr-ea or I missed it ?

### ISSUE THREAD

**Issue by 32l** [huawei-noah/vega#30]
Hi, thanks for your awesome work, but i doubt whether the implement of  EA's mutation  is correct, the paper says that we should acquire the block credits during model evaluation procedure, which can be used to guide the mutation to accelerate searching and find better architecture, I find that vega's implementation is general mutaion, could you help me? thanks!

**Comment by zhangjiajin** [comment]
Please check file: `vega/algorithms/nas/esr_ea/esr_ea_individual.py`

```python
    def mutation_node(self, mutation_rate=0.05):
        """Mutate the active node type of individual.
        :param mutation_rate: the prosibility to mutate, defaults to 0.05
        :type mutation_rate: float
        """
        for node_ind in range(self.node_num):
            if self.gene[node_ind][0] and np.random.rand() < mutation_rate:
                type_prob = self.net_info.func_prob
                self.gene[node_ind][1] = bisect_right(type_prob, random())
        self.active_net = self.active_net_list()
        self.parameter = self.network_parameter()
        self.flops = self.network_flops()
```

It's guided mutation, not normal mutation.
The `func_prob` is `guide information`.

**Comment by 32l** [comment]
ok, thanks.  I will double check the code.
