### ISSUE TITLE
Where can I find SPNetXB_COCO_ImageNetPretrained.pth ?

### ISSUE THREAD

**Issue by AyeshaNirma** [huawei-noah/vega#36]
With reference to the issue #14. Can you please tell where can I find this model `SPNetXB_COCO_ImageNetPretrained.pth` ?

**Comment by zhangjiajin** [comment]
here: <http://www.noahlab.com.hk/opensource/vega/models/pretrained/SPNetXB_COCO_ImageNetPretrained.pth>
