### ISSUE TITLE
some code is missing in quick_start.md 

### ISSUE THREAD

**Issue by bazige** [huawei-noah/vega#4]
in vega/docs/cn/developer/quick_start.md
```
@NetworkFactory.register(NetTypes.CUSTOM)

    def __init__(self, desc):
        super(SimpleCnn, self).__init__()
```
it may be missing this code：
class SimpleCnn(nn.Module):

**Comment by zhangjiajin** [comment]
Yes. The code in the documentation lacks the definition of the class. Thank you for discovering this error. @bazige
