### ISSUE TITLE
Can not find the auto_lane pretrained pth.

### ISSUE THREAD

**Issue by mengzhibin** [huawei-noah/vega#43]
What's more, is there any test code or inference code guide of auto_lane module?

**Comment by mengzhibin** [comment]
I have found the pretrained tar file, close this issue

**Comment by mengzhibin** [comment]
1. AutoLane tar file cannot been download
https://github.com/huawei-noah/vega/blob/master/docs/cn/model_zoo/model_zoo.md
Is the download site wrong?
2. Only pretrained model on culane is uploaded, can i ask when the curve lanes based model been uploaded?

**Comment by Smellly** [comment]
@mengzhibin
Hi, do you figure it out how to do a inference with culane pretrained model?
