### ISSUE TITLE
question about generate the ground truth

### ISSUE THREAD

**Issue by hitczr** [huawei-noah/vega#49]
When the two lane lines are so close that they are in the same grid. Which lane line the grid will respond to？

And another question is about the adaptive score masking:
what does the uxf and uyf mean?

**Comment by zhangjiajin** [comment]
@sptj

**Comment by sptj** [comment]
>When the two lane lines are so close that they are in the same grid. Which lane line the grid will respond to？

You can get the result by carefully reading the [auto_lane_datasets](https://github.com/huawei-noah/vega/blob/master/vega/datasets/pytorch/auto_lane_datasets.py)
