### ISSUE TITLE
SP-NAS Config file for EuroCity Persons model

### ISSUE THREAD

**Issue by AyeshaNirma** [huawei-noah/vega#59]
I am trying to reproduce numbers for EuroCityPersons using your pre-trained model in the Zoo. I have downloaded model from zoo for [ECP](https://github.com/huawei-noah/vega/blob/master/docs/en/model_zoo/model_zoo.md). However, the corresponding config file is missing. Can you please provide it.

**Comment by zhangjiajin** [comment]
Sorry, Vega no longer supports ECP datasets.
