### ISSUE TITLE
Fully train of pba

### ISSUE THREAD

**Issue by DanceInDark** [huawei-noah/vega#61]
Hi, I have run pba and get some augment policies. But I do not known how to fully train the model with the found policy. Could you help me?

**Comment by zhangjiajin** [comment]
Bug is fixed, please try it again.
@DanceInDark

**Comment by zhangjiajin** [comment]
The config file: <https://github.com/huawei-noah/vega/blob/master/benchmark/algs/data_augmentation/pba.yml>
@DanceInDark

**Comment by DanceInDark** [comment]
> Bug is fixed, please try it again.
> @DanceInDark

Good work. I am trying it again.
