### ISSUE TITLE
[URL fail] lackness of URL for pre-trained model source. 

### ISSUE THREAD

**Issue by wjwangppt** [huawei-noah/vega#62]
I found that we cannot download the pretrained models which vega provided in this page `https://github.com/huawei-noah/vega/blob/master/docs/cn/user/examples.md`.
 Can you fix the url links of pre-trained models or provide other ones?

**Comment by zhangjiajin** [comment]
The URL has been fixed. Please try again.
@wjwangppt

**Comment by wjwangppt** [comment]
> The URL has been fixed. Please try again.
> @wjwangppt

Thanks! It works.
