### ISSUE TITLE
Can auto Lane detect any number of lanes?

### ISSUE THREAD

**Issue by norainnosun** [huawei-noah/vega#66]
Dose  auto Lane limited to detect a pre-defined number of lanes? thanks

**Comment by zhangjiajin** [comment]
@sptj

**Comment by mengzhibin** [comment]
So the parameters of auto lane trained by curvelanes will not be released?

**Comment by sptj** [comment]
@norainnosun No，it does not. CurveLane-NAS is desiged to detect lanes in the wild for industry requirements, any number of lanes are compatible.

**Comment by norainnosun** [comment]
thanks for your reply
