### ISSUE TITLE
Why VEGA?

### ISSUE THREAD

**Issue by CyFeng16** [huawei-noah/vega#74]
Thanks for the open-source and continuous maintenance of VEGA. Why is VEGA, is there any story? :)

**Comment by zhangjiajin** [comment]
Zhinü (织女, the weaver girl, symbolizing the star Vega) is a fairy in ancient Chinese myths and legends. She's responsible for providing the fairy's clothes and clouds. We hope that Vega will provide AI research and application infrastructure like a weaver girl.

**Comment by CyFeng16** [comment]
@zhangjiajin It's COOOOL! 
Appreciate your reply and hope this project can be widely accepted and used by the community as well.
