### ISSUE TITLE
I have two GPUs, how to choose one of them to work?

### ISSUE THREAD

**Issue by AwSheng** [huawei-noah/vega#75]
Hello：

I did not find the code for GPU selection.

Thank you ！

**Comment by AwSheng** [comment]
If my GPU0 is working, I cannot use GPU1 to run the code.

**Comment by fengChenHPC** [comment]
you can try CUDA_VISIBLE_DEVICES

**Comment by AwSheng** [comment]
> 您可以尝试CUDA_VISIBLE_DEVICES
Think you very much!! It worked!

**Comment by AwSheng** [comment]
> you can try CUDA_VISIBLE_DEVICES
Thank you very much ！ It worked！
