### ISSUE TITLE
Question on "auto_lane_pointlane_codec.py"

### ISSUE THREAD

**Issue by shenqingzhou** [huawei-noah/vega#83]
hello! I'm wondering when the result of `(self.points_per_line / self.feature_height)` is not integer, will this line have some problems? (by default it's 72/18=4)
https://github.com/huawei-noah/vega/blob/698b6c009c83763870eb1e5db76bde147010b805/zeus/datasets/common/utils/auto_lane_pointlane_codec.py#L289
should it be `center_y = y_list[int((self.points_per_line / self.feature_height) * (self.feature_height - 1 - h))] `?

**Comment by zhangjiajin** [comment]
@sptj
