### ISSUE TITLE
wrong implementation for DARTS?

### ISSUE THREAD

**Issue by runninghack** [huawei-noah/vega#85]
In [super_network.py](https://github.com/huawei-noah/vega/blob/master/zeus/networks/super_network.py#L79), you have 

`self.initializer()`

Is that a mistake? If not, why you initialize all the hyperparameters everything the model is called?

**Comment by zhangjiajin** [comment]
This method initializes the architecture parameters but does not initialize the network weights.

**Comment by runninghack** [comment]
Yes, I understand what's being updated there are architecture parameters. It doesn't make sense to me to initialize the architecture parameters though for every batch of data. Shouldn't they be initialized only in the beginning and updated throughout the whole process with Darts?

**Comment by zhangjiajin** [comment]
You're right. There's a problem with repeated initialization. This problem is introduced to be compatible with TF. For PyTorch, the initialization is incorrect. This line needs to be deleted. We'll fix this bug as soon as possible.
Thank you very much!
@runninghack
