### ISSUE TITLE
The performance of CARS from example

### ISSUE THREAD

**Issue by macaca50507** [huawei-noah/vega#86]
Hi, thanks for the great work!
I am curious about the output I get from cars algorithm in the examples.
I got 86.488 as best top-1 valid accuracy after running the command given in readme.
Should the accuracy suppose to be more higher or I need to modify the cars.yml for better performance.

**Comment by zhangjiajin** [comment]
@macaca50507 
Hi, please run benchmark config:

```bash
python3 ./run_pipeline.py ./nas/cars/cars.yml -s b
```
