### ISSUE TITLE
PRUNE_EA  parallel_search error

### ISSUE THREAD

**Issue by wnov** [huawei-noah/vega#87]
when I set parallel_search: True in prune.yml, I get this error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/wn/vega/zeus/trainer_base.py", line 153, in train_process
    self._train_loop()
  File "/wn/vega/zeus/trainer_base.py", line 279, in _train_loop
    self.callbacks.before_train()
  File "/wn/vega/zeus/trainer/callbacks/callback_list.py", line 139, in before_train
    callback.before_train(logs)
  File "/wn/vega/vega/algorithms/compression/prune_ea/prune_trainer_callback.py", line 61, in before_train
    self.latency_count = calc_forward_latency(self.trainer.model, count_input, sess_config)
  File "/wn/vega/zeus/metrics/forward_latency.py", line 30, in calc_forward_latency
    step_cfg = UserConfig().data.get("nas")
AttributeError: 'NoneType' object has no attribute 'get'

Its all fine to set parallel_search:False and run prune algo demo, whats wrong with parallel_search

**Comment by wnov** [comment]
> when I set parallel_search: True in prune.yml, I get this error
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/wn/vega/zeus/trainer_base.py", line 153, in train_process
> self._train_loop()
> File "/wn/vega/zeus/trainer_base.py", line 279, in _train_loop
> self.callbacks.before_train()
> File "/wn/vega/zeus/trainer/callbacks/callback_list.py", line 139, in before_train
> callback.before_train(logs)
> File "/wn/vega/vega/algorithms/compression/prune_ea/prune_trainer_callback.py", line 61, in before_train
> self.latency_count = calc_forward_latency(self.trainer.model, count_input, sess_config)
> File "/wn/vega/zeus/metrics/forward_latency.py", line 30, in calc_forward_latency
> step_cfg = UserConfig().data.get("nas")
> 
> Its all fine to set parallel_search:False and run prune algo demo, whats wrong with parallel_search

My config set as follow:
general:
    parallel_search: True
    parallel_fully_train: True
    backend: pytorch
    quota:
        restrict:
            flops: 10.0

pipeline: [nas]
# pipeline: [nas, fully_train]

nas:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /home/Code/AutoML/vega/zeus/networks/pytorch/customs/cache/datasets/cifar10/
            train_portion: 0.9
        test:
            batch_size: 256

    search_algorithm:
        type: PruneEA
        codec: PruneCodec
        policy:
            length: 464
            num_generation: 5
            num_individual: 4
            random_models: 5

    search_space:
        type: SearchSpace
        modules: ['backbone', 'head']
        backbone:
            type: ResNetGeneral
            stage: 3
            base_depth: 20
            base_channel: 16
        head:
            type: LinearClassificationHead
            base_channel: 64
            num_classes: 10

    trainer:
        type: Trainer
        callbacks: PruneTrainerCallback
        epochs: 1
        init_model_file: "./cache/models/resnet20"
        optimizer:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: !!float 1e-4
        lr_scheduler:
            type: StepLR
            params:
                step_size: 20
                gamma: 0.5
        loss:
            type: CrossEntropyLoss
            params:
                sparse: True
        seed: 10
        cuda: False
    # evaluator:
    #     type: Evaluator
    #     gpu_evaluator:
    #         type: GpuEvaluator
    #         metric:
    #             type: accuracy

#        davinci_mobile_evaluator:
#            type: DavinciMobileEvaluator
#            hardware: "Davinci"
#            remote_host: "http://192.168.0.2:8888"

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "./tasks/0104.211641.898/output/nas"

    dataset:
        ref: nas.dataset
        common:
            train_portion: 1.0

    trainer:
        ref: nas.trainer
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [200,300,375]
                gamma: 0.1

benchmark:
    pipeline: [nas, fully_train, benchmark_cifar10]
    nas:
        dataset:
            test:
                batch_size: 1024
        search_algorithm:
            policy:
                num_generation: 31
                num_individual: 32
                random_models: 64
    fully_train:
        trainer:
            epochs: 400
    benchmark_cifar10:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: nas.dataset
            common:
                train_portion: 1.0
        evaluator:
            type: Evaluator
            gpu_evaluator:
                type: GpuEvaluator
                metric:
                    type: accuracy

**Comment by zhangjiajin** [comment]
The demo has a bug, please comment out the following code in `zeus/metrics/forward_latency.py`:

```python
def calc_forward_latency(model, input, sess_config=None, num=100):
    """Model forward latency calculation.

    :param model: network model
    :type model: torch or tf module
    :param input: input tensor
    :type input: Tensor of torch or tf
    :param num: forward number
    :type num: int
    :return: forward latency
    :rtype: float
    """
    # step_cfg = UserConfig().data.get("nas")
    # if hasattr(step_cfg, "evaluator"):
    #     evaluate_cfg = step_cfg.get("evaluator")
    #     if hasattr(evaluate_cfg, "davinci_mobile_evaluator"):
    #         evaluate_config = evaluate_cfg.get("davinci_mobile_evaluator")
    #         latency = _calc_forward_latency_davinci(model, input, sess_config, evaluate_config)
    # else:
    latency = _calc_forward_latency_gpu(model, input, sess_config, num)
    return latency
```

Note that the value of random_models must be greater than the number of GPUs.

```yaml
    search_algorithm:
        type: PruneEA
        codec: PruneCodec
        policy:
            length: 464
            num_generation: 31
            num_individual: 32
            random_models: 64
```

@wnov
