### ISSUE TITLE
how to run the auto_lane

### ISSUE THREAD

**Issue by zhangjy2008327** [huawei-noah/vega#92]
I want to run the auto_lane according to the user guide but get the errors. the configure files have changed, but the command recommended is not changed
how to configure the right files of lane detection?
how to register the class name before using them?
how to study the Curvelane-NAS algorithms step by step? 
 for example, 
how to configure the yaml file in some dir some file, how to set the weight between the background and the lane lines (0.4 vs 1.0 maybe not fit for some model according to my experiments of SCNN? because their mIOU only about 0.105 if the weight of the background is set 0.4, the lane lines' weights are set to 1.0. So it is not possible to use mIOU 0.5 to calculate whether the corresponding lane line exists. 
please give detailed parameters of your when training and testing on curve lane dataset)
.........

I have read the sure guide carefully, but I don't know how to handle the questions above.
please solve the problems or update the corresponding guide

**Comment by zhangjiajin** [comment]
@zhangjy2008327

**Comment by zhangjiajin** [comment]
how to configure the right files of lane detection?
-- Based on the configuration file in the example, indicate the nodes you want to adjust.

how to register the class name before using them?
-- Which classes do you want to register?

how to study the Curvelane-NAS algorithms step by step?
-- [algorithm referenc](https://github.com/huawei-noah/vega/blob/master/docs/en/algorithms/auto_lane.md) -> [paper](https://arxiv.org/abs/2007.12147) -> [examples reference](https://github.com/huawei-noah/vega/blob/master/docs/en/user/examples.md) -> [configuration reference](https://github.com/huawei-noah/vega/blob/master/docs/en/user/config_reference.md)

@zhangjy2008327
