### ISSUE TITLE
AutoLaneHead forward error

### ISSUE THREAD

**Issue by lhcalibur** [huawei-noah/vega#94]
Error caused by super class's Module function: forward; When training, Cls AutoLaneHead's function forward_train is not called.

**Comment by zhangjiajin** [comment]
Please provide the error stack information when an error occurs.

@lhcalibur

**Comment by zhangjiajin** [comment]
@lhcalibur 
Vega 1.3 is released now. The Auto-lane bug is fiexed.
Please try it again.
