### ISSUE TITLE
Error occurs when running the example of autoLane

### ISSUE THREAD

**Issue by TangChangcheng** [huawei-noah/vega#96]
![image](https://user-images.githubusercontent.com/21055189/108448866-77c89c80-729d-11eb-92f3-065dd2b76fcc.png)

What should I do to debug this error? Thank you

**Comment by zhangjiajin** [comment]
@TangChangcheng 

The size of the input image may not match.
Is the YML configuration file in the Examples directory?
What dataset is used?

**Comment by TangChangcheng** [comment]
> @TangChangcheng
> 
> The size of the input image may not match.
> Is the YML configuration file in the Examples directory?
> What dataset is used?

Yes, I ran the YML configuration file in `examples/nas/auto_lane/auto_lane.yaml`. Here's the dataset configuration:
![image](https://user-images.githubusercontent.com/21055189/108487503-4c17d780-72da-11eb-9fff-b80582abc42e.png)

**Comment by zhangjiajin** [comment]
Please provide complete YAML file and running logs (./tasks/<task id>/logs/*).

@TangChangcheng

**Comment by TangChangcheng** [comment]
[config_and_log.zip](https://github.com/huawei-noah/vega/files/6028022/config_and_log.zip)

Here is my configuration and log files. @zhangjiajin

**Comment by zhangjiajin** [comment]
@TangChangcheng 

According to the logs provided by you, the bugs of AutoLane are found and have been incorporated into the latest code.
Currently, there is a bug that is not resolved. As a result, the parallel function is unavailable. The latest sample configuration file does not support parallel processing.

We'll update the version by the middle of next month, and the new version will support parallelism.

Thank you for your support!

**Comment by zhangjiajin** [comment]
@TangChangcheng 
We released Vega v1.3. The Auto-Lane bug is fixed. Please try it again.
