### ISSUE TITLE
How to test CARS results after full-train

### ISSUE THREAD

**Issue by Chouk1** [huawei-noah/vega#98]
I am sorry but it is puzzling on how to test CARS after training finishes. I have got the network architecture files desc_X.json and the saved models model_X.pth. So my problem is do I use the results after training to test these outputs myself.

**Comment by zhangjiajin** [comment]
Please see the following code:

<https://github.com/huawei-noah/vega/blob/master/vega/tools/inference.py>

Or view the help information of the following command:

```bash
python3 -m vega.tools.inference -h
```

**Comment by Chouk1** [comment]
> Please see the following code:
> 
> https://github.com/huawei-noah/vega/blob/master/vega/tools/inference.py
> 
> Or view the help information of the following command:
> 
> ```shell
> python3 -m vega.tools.inference -h
> ```

Thank u so much !
